### ISSUE TITLE
Capture powerstat data on jobs with and without VAAPI enabled.

### ISSUE THREAD

**Issue by pieqq** [canonical/checkbox-kivu#11]
Comparing powerstat data (with and without vaapi) might be a good option to identify any power regressions. Majority of the power regressions would be captured by CPU usage comparison (see #10), but power regressions due to device failures (eg. something going wrong in audio/camera devices) may not be captured by this flow.

**Comment by petitfou** [comment]
This has been somehow done in the provider with the energy saving test
